version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - compute_6942
      - compute_6943
      - compute_6944
      - auth
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  compute_6942:
    build: ./compute_server
    environment:
      - PORT=6942
    expose:
      - "6942"
    ports:
      - "6942:6942"
    env_file: 
      - ./.env

  compute_6943:
    build: ./compute_server
    environment:
      - PORT=6943
    expose:
      - "6943"
    ports:
      - "6943:6943"
    env_file: 
      - ./.env

  compute_6944:
    build: ./compute_server
    environment:
      - PORT=6944
    expose:
      - "6944"
    ports:
      - "6944:6944"
    env_file: 
      - ./.env

  auth:
    build: ./auth_server
    expose:
      - "6969"
    ports:
      - "6969:6969"
    env_file: 
      - ./.env
